### ISSUE TITLE
Sometimes LineChart doesn't set its y-axis domain to fit all of the data

### ISSUE THREAD

**Issue by justinanderson** [CxSci/SA-dashboard#159]
<img width="200" src="https://user-images.githubusercontent.com/244952/123999242-4a54d380-d9a0-11eb-83e0-61c3487788de.png">

It might make sense to replace the `domain={['auto', 'auto']}` in [LineChartMetric](https://github.com/CxSci/SA-dashboard/blob/master/src/components/charts/LineChartMetric.js#L77) with something we calculate ourselves.

**Comment by gerardott** [comment]
There is a problem with the data in geojson file.
In the pair `{year, value}`, value is a string with a number and should be a number:
`{"year": "2019", "value": "67"}, {"year": "2020 Predicted", "value": 65}`
