### ISSUE TITLE
Explore using POI data from Foursquare

### ISSUE THREAD

**Issue by mohsenmailbox** [CxSci/SA-dashboard#18]
use open street maps to add POI data to the dashboard in order to answer "what is in there?" question

**Comment by justinanderson** [comment]
Probably doable with OSM's [Overpass API}(https://wiki.openstreetmap.org/wiki/Overpass_API). OSM doesn't know SA2s or SA1s, but it should be possible to request results within an arbitrary polygon. It may be pretty slow, so we'll probably want to cache results.

Also, we're limited to searching by the [properties OSM uses](https://wiki.openstreetmap.org/wiki/Key:amenity), so we'll need to define our categories based around that list.

**Comment by justinanderson** [comment]
Renamed issue to more accurately reflect what we're up to. OSM's amenities aren't broken into categories useful to this project, but Foursquare's Places API is.

Whether any deployment of this project actually uses Foursquare's Places API will depend on the financial constraints of those running the server. The current use case for POI data (counts of POI in each SA2 grouped by category) is only feasible using Foursquare's Places Database, which involves a substantial yearly fee.

There may be other use cases, like simply viewing POIs on the map, which might be able to use the less costly Places API.

**Comment by justinanderson** [comment]
Added placeholder POI data from OSM just so the "Businesses" map layer can be worked on, but a better source like Foursquare should be used in the final version.

Closing, since the issue of POI data has been explored. It's now a decision for those hosting the service whether they want to acquire better POI data.
