### ISSUE TITLE
Make sure layout looks the same across browsers

### ISSUE THREAD

**Issue by justinanderson** [CxSci/SA-dashboard#19]

**Comment by mohsenmailbox** [comment]
+ there is a text box 
"Select a community to learn more about opportunity in that area." 
the text box covers the sidebar
While keeping the textbox in the page, we need to change sidebar structure in a way that this problem does not happen

**Comment by justinanderson** [comment]
Closing as resolved. If we have any specific browser problems in the future, we can open new issues as needed.
