### ISSUE TITLE
Make map popups lead to detail pages

### ISSUE THREAD

**Issue by justinanderson** [CxSci/SA-dashboard#227]
Add a [chevron](https://mui.com/components/material-icons/?query=chevron&selected=ChevronRight) to MapPopupContent when it's expanded, like the popup in [this Figma mockup](https://www.figma.com/file/yaKUmuZM9xPQ1Qq5YVf5Yu/Design---Skills?node-id=3206%3A31143).

The title and chevron should be link to the detail page for the highlighted region. The link should be of the format `{baseURL}/explore/{dataset}/{id}`, e.g. Adelaide would be http://localhost:3000/explore/small-business/401011001.

Purple outline here to show the link's clickable area.
<img src="https://user-images.githubusercontent.com/244952/160143408-e54e82e9-82fa-4426-8f9e-f5b55b2dc570.png" width="208" /><img src="https://user-images.githubusercontent.com/244952/160143422-c3751d06-81ae-4abc-a24a-ba7b9ec7d91e.png" width="208" />

**Comment by torosyaneric** [comment]
PR: https://github.com/CxSci/SA-dashboard/issues/227
