### ISSUE TITLE
problem with origin and destination of flow paths

### ISSUE THREAD

**Issue by mohsen-bahrami** [CxSci/SA-dashboard#28]
For some SA2 regions the paths start from points out of the region, probably because of the shape of the region and geo-center xy falls somewhere out of that region
Examples:
OUTBACK 
West Coast

**Comment by justinanderson** [comment]
We're using Turf.js in the project already, so http://turfjs.org/docs/#pointOnFeature maybe be useful here.

**Comment by LeoSilvaGomes** [comment]
> We're using Turf.js in the project already, so http://turfjs.org/docs/#pointOnFeature maybe be useful here.

I tried to use this feature (pointOnFeature( )) that @justinanderson suggested, and it doesn't work.
This feature returns the same value as the "center( )" feature that we are already using in the application.

![image](https://user-images.githubusercontent.com/61520601/96186870-70ba0800-0f12-11eb-9195-57150262e8e7.png)

![image](https://user-images.githubusercontent.com/61520601/96186772-49fbd180-0f12-11eb-932e-7845ebd41237.png)

In the first picture, you can see how I am using the turf.js features, and in the second picture, the return o each o them.

**Comment by justinanderson** [comment]
I think the third line should actually be:
```js
var pointOnFeature = turf.pointOnFeature(ft).geometry.coordinates;
```
Each SA2 is already a feature containing a MultiPolygon, so it makes sense you'd get the regular center back if you make a single Polygon of a MultiPolygon.

That said, even when the methods work as intended, `pointOnFeature`, `centroid`, and `centerOfMass` are all insufficient to fix this issue. They do move points inside of features, but only just.

We may have to hardcode some points for problematic SA2s. I haven't seen more than a handful myself, but it could be a tedious job. @mohsenmailbox, would you say fixing this is a priority?

**Comment by mohsenmailbox** [comment]
not a priority

**Comment by justinanderson** [comment]
We ended up not displaying flows between regions.

For posterity, the solution would have been to use a library like https://github.com/mapbox/polylabel.
