### ISSUE TITLE
problem with loading of outflow

### ISSUE THREAD

**Issue by LeoSilvaGomes** [CxSci/SA-dashboard#33]
In some regions, the outflow option crashes.
Examples:
FLAGSTAFF HILL
HAPPY VALLEY

In the regions cited, I noticed that just two areas link in the outflow option, which can bug: showing a white page or removing the arrow direction animation.

**Comment by mohsenmailbox** [comment]
yes, this is because those area trade or visit lass than 3 other regions (in the provided data)

**Comment by justinanderson** [comment]
We ended up not displaying flows between regions.
