### ISSUE TITLE
Show names of SA2s on mouseover and selection

### ISSUE THREAD

**Issue by mohsenmailbox** [CxSci/SA-dashboard#37]
~shows SA2 names when hovering over the area~

Edited by @justinanderson.

When the cursor is over a map region, that region's name should show in some way so a user doesn't have to click on each SA2 to see what its name is.

Similarly, the names of SA2s should show up on the map when they are selected and when they are the origin or destination of flow lines.

**Comment by mohsenmailbox** [comment]
add info icon next to metrics in sidebar, 
shows information about the metric when hovering over the icon

**Comment by justinanderson** [comment]
This is resolved by earlier PRs from @LeoSilvaGomes and @annika608. The bit about tooltips is tracked by #22.
