### ISSUE TITLE
Mock up dashboard UI

### ISSUE THREAD

**Issue by justinanderson** [CxSci/SA-dashboard#7]
The planned features are getting complex enough that we need wireframe mockups so contributors can reason about how the dashboard work as a whole.

The dashboard interface should be mostly a map with some navigation for reaching static pages, some method for switching between the type of data to visualize, some method for filtering and searching the given data, and some method for showing details about specific areas.

I'll add some simple wireframes to this issue to get the discussion started on how things should work.

**Comment by justinanderson** [comment]
These sketches are just to get the conversation going and are not at all final. Everything is drawn too big. Please suggest changes. This is mostly aping [inequality.media.mit.edu](https://inequality.media.mit.edu/)'s design.

When a user visits the dashboard, they want to do 1 of 3 things:

1. Learn more about the dashboard itself, which they can do by visiting one of the static pages linked at the top right of the page.

2. Change what data the dashboard displays, which they can do in the panel on the right either by changing which data layer is active in the "Layers" dropdown or adjusting filters on attributes of the selected data layer, such as narrowing to a specific age range or ignoring certain categories of business.

    inequality.media.mit.edu has a similar interface for filtering grouped data when both axes are numeric and when one axis is text.

3. Select a specific SA2 either by selecting it directly on the map or searching via an autocompleting search field in the top left of the map. Doing so replaces the panel of filters with a panel of location details, which can be dismissed by clicking the X in the panel, the X in the search, or clicking in the ocean so that no region is selected.

There are also areas for a legend and any logos for project sponsors that need to be on display.

These screens are in order of that one use case:

1. Load the site:
![00-Initial-State](https://user-images.githubusercontent.com/244952/92199428-2474a600-ee45-11ea-8cc2-46461525befb.png)

2. Select a data layer:

![01-Changing-Layers](https://user-images.githubusercontent.com/244952/92199503-5e45ac80-ee45-11ea-97d8-86572d0ed607.png)

3. Search for a location:

![02-Searching](https://user-images.githubusercontent.com/244952/92199540-71f11300-ee45-11ea-975e-6073cc432a24.png)

4. View its details:

![03-Location-Detail](https://user-images.githubusercontent.com/244952/92199567-859c7980-ee45-11ea-99a5-3ac914fc5178.png)

**Comment by LeoSilvaGomes** [comment]
## Suggestions

- Putting the search component in the navbar it can let the map area cleaner.
- Legend:
Refactoring the size of the colors on the legend component.
![photo_2020-09-04_14-42-51](https://user-images.githubusercontent.com/61520601/92270742-ef0b9f00-eebc-11ea-982f-f4c94db7072b.jpg)


## Ideas

- Introductory information
    - First idea - Hover icon
![Projeto - Drawing 12408283394221876049](https://user-images.githubusercontent.com/61520601/92270635-c5eb0e80-eebc-11ea-8e20-dea60f3bb0e9.png)

    - Second idea - Modal component with checkbox with "I don't want to visualize it anymore" or another text.
![Projeto - Drawing 13877856781701438660](https://user-images.githubusercontent.com/61520601/92270641-c84d6880-eebc-11ea-931f-38e5aa2a592d.png)
