### ISSUE TITLE
Add financial data layer

### ISSUE THREAD

**Issue by justinanderson** [CxSci/SA-dashboard#8]
This depends on the result of #5. We need to know if the financial dataset can be used for a public site or if it needs to change.

How this will work also depends on UI decisions in #7.

The basic idea of the layer should be similar to the mobility layer: color each SA2 by magnitude of an attribute in the dataset, present details for a selected SA2 in the detail panel, allow users to filter the dataset and visualization by some attributes like age range and type of activity.

**Comment by mohsenmailbox** [comment]
Only one layer for example called "Economic activity" in the sidebar drop down menu 
-Financial transactions grouped by age range
-Financial transactions grouped by type of business
and user can choose which of those two to see after bringing up the layer map
choosing by radio buttons "group by age" and "group by business"
one can be chosen at a time
